stages:
  data_ingestion:
    cmd: python src/cnnClassfier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassfier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/cnnClassfier/pipeline/stage02_base_model.py
    deps:
      - src/cnnClassfier/pipeline/stage02_base_model.py
      - config/config.yaml
    params:
      - IMAZE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassfier/pipeline/stage_03_train.py
    deps:
      - src/cnnClassfier/pipeline/stage_03_train.py
      - src/cnnClassfier/components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAZE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassfier/pipeline/stage_04_evaluation.py
    deps:
      - src/cnnClassfier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAZE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
